---
version: "3"
services:
  xbvr:
    hostname: "xbvr"
    container_name: "xbvr"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/xbapps/xbvr:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/xbvr:/root/.config/xbvr:rw"
      - "unionfs:/mnt"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=false"
      - "traefik.http.routers.xbvr-rtr.entrypoints=https"
      - "traefik.http.routers.xbvr-rtr.rule=Host(`xbvr.${DOMAIN}`)"
      - "traefik.http.routers.xbvr-rtr.tls=true"
      - "traefik.http.routers.xbvr-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.xbvr-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.xbvr-rtr.service=xbvr-svc"
      - "traefik.http.services.xbvr-svc.loadbalancer.server.port=9999"
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/
